# Cloudflare DDNS — updates DNS A records when ISP IP changes
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ddns

resources:
- cloudflare-ddns.cronjob.yaml

secretGenerator:
- name: cloudflare-ddns-api-token
  envs:
  - cloudflare-ddns-api-token.env
  options:
    disableNameSuffixHash: true
